# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Graham Patrick Earley
email: graham@grahamearley.website
description: Graham Earley's blog.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://grahamearley.website" # the base hostname & protocol for your site
github_username:  grahamearley
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
